---
- name: Ensure Nginx is installed
  package:
    name: nginx
    state: present

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
  notify: Restart Nginx

- name: Ensure Nginx service is enabled and running
  service:
    name: nginx
    state: started
    enabled: true

