name: Execute Ansible Syntax Checks

on:
  push:
    branches:
      - dev

jobs:
  execute-ansible-testing:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible ansible-lint; sudo mkdir logs && sudo chmod 777 logs/;

      - name: Run Ansible Syntax Check
        run: |
          ansible-playbook -vvv --syntax-check -i inventory/hosts.yml playbooks/*

      - name: Run Ansible Lint
        run: |
          ansible-lint -vvvv -x ANSIBLE0010 -x 401 playbooks/*

      - name: Validate Inventory
        run: |
          ansible-inventory -vvv -i inventory/hosts.yml --list

      - name: Validate Variable Definitions
        run: |
          ansible-playbook -vvv -i inventory/hosts.yml playbooks/* --list-tasks
